"""add data_summary and user_context to files

Revision ID: aac4786a6d7e
Revises: 51d8a5c5b7c3
Create Date: 2026-02-03 10:15:14.454526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac4786a6d7e'
down_revision: Union[str, Sequence[str], None] = '51d8a5c5b7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('data_summary', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('user_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'user_context')
    op.drop_column('files', 'data_summary')
    # ### end Alembic commands ###
