"""State schemas for LangGraph agent workflows."""

from typing import Annotated, TypedDict
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages


class OnboardingState(TypedDict):
    """State for the Onboarding Agent workflow.

    This agent analyzes uploaded datasets and generates comprehensive summaries
    including structure, quality, semantics, and sample data.
    """

    file_id: str
    """Unique identifier for the uploaded file."""

    file_path: str
    """Absolute path to the uploaded file on disk."""

    user_context: str
    """Optional context provided by user during upload (e.g., 'Sales data from Q4 2025')."""

    data_profile: str
    """Pandas profiling output as JSON string (structure, types, stats)."""

    data_summary: str
    """LLM-generated natural language summary of the dataset."""

    sample_data: str
    """First few rows formatted as a string for user verification."""

    error: str
    """Error message if processing fails, empty string if successful."""


class ChatAgentState(TypedDict):
    """State for the Chat Agent workflow.

    Orchestrates Coding Agent → Code Checker → Execute → Data Analysis Agent
    with retry loops for validation failures.
    """

    file_id: str
    """Unique identifier for the file being analyzed."""

    user_id: str
    """User ID for access control."""

    user_query: str
    """User's natural language data analysis query."""

    data_summary: str
    """Data summary from Onboarding Agent (loaded into chat context)."""

    data_profile: str
    """Structured JSON data profile with column names, types, and sample data."""

    user_context: str
    """Accumulated user context and refinements."""

    file_path: str
    """Absolute path to the user's uploaded data file on the server."""

    generated_code: str
    """Python code generated by Coding Agent."""

    validation_result: str
    """Validation outcome: 'VALID' or error details."""

    validation_errors: list[str]
    """List of validation error messages from Code Checker."""

    error_count: int
    """Retry counter for validation loop (increments on each retry)."""

    max_steps: int
    """Maximum allowed retry attempts (default: 3)."""

    execution_result: str
    """Output from code execution (result variable as string)."""

    analysis: str
    """Data Analysis Agent's interpretation of execution results."""

    messages: Annotated[list[AnyMessage], add_messages]
    """Conversation history with automatic accumulation via add_messages reducer."""

    final_response: str
    """Final response to send back to user."""

    error: str
    """Error message if workflow fails, empty string if successful."""
