"""State schemas for LangGraph agent workflows."""

from typing import Annotated, Literal, TypedDict

from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field


class RoutingDecision(BaseModel):
    """Manager Agent's routing decision for query classification.

    Determines which route a user query should take through the agent pipeline:
    - MEMORY_SUFFICIENT: Answer from conversation history (no code generation)
    - CODE_MODIFICATION: Modify existing code (incremental changes)
    - NEW_ANALYSIS: Generate fresh code from scratch
    """

    route: Literal["MEMORY_SUFFICIENT", "CODE_MODIFICATION", "NEW_ANALYSIS"]
    reasoning: str = Field(description="Brief explanation of why this route was chosen")
    context_summary: str = Field(description="Relevant context from conversation for downstream agents")
    chart_hint: str = Field(default="", description="Suggested chart type if query implies visualization (bar, line, scatter, pie, histogram, box, or empty string)")


class OnboardingState(TypedDict):
    """State for the Onboarding Agent workflow.

    This agent analyzes uploaded datasets and generates comprehensive summaries
    including structure, quality, semantics, and sample data.
    """

    file_id: str
    """Unique identifier for the uploaded file."""

    file_path: str
    """Absolute path to the uploaded file on disk."""

    user_context: str
    """Optional context provided by user during upload (e.g., 'Sales data from Q4 2025')."""

    data_profile: str
    """Pandas profiling output as JSON string (structure, types, stats)."""

    data_summary: str
    """LLM-generated natural language summary of the dataset."""

    sample_data: str
    """First few rows formatted as a string for user verification."""

    error: str
    """Error message if processing fails, empty string if successful."""


class ChatAgentState(TypedDict):
    """State for the Chat Agent workflow.

    Orchestrates Coding Agent -> Code Checker -> Execute -> Data Analysis Agent
    with retry loops for validation failures.

    Extended in v0.4 with visualization fields for chart generation pipeline.
    """

    file_id: str
    """Unique identifier for the file being analyzed."""

    user_id: str
    """User ID for access control."""

    user_query: str
    """User's natural language data analysis query."""

    data_summary: str
    """Data summary from Onboarding Agent (loaded into chat context)."""

    data_profile: str
    """Structured JSON data profile with column names, types, and sample data."""

    user_context: str
    """Accumulated user context and refinements."""

    file_path: str
    """Absolute path to the user's uploaded data file on the server."""

    generated_code: str
    """Python code generated by Coding Agent."""

    validation_result: str
    """Validation outcome: 'VALID' or error details."""

    validation_errors: list[str]
    """List of validation error messages from Code Checker."""

    error_count: int
    """Retry counter for validation loop (increments on each retry)."""

    max_steps: int
    """Maximum allowed retry attempts (default: 3)."""

    execution_result: str
    """Output from code execution (result variable as string)."""

    analysis: str
    """Data Analysis Agent's interpretation of execution results."""

    messages: Annotated[list[AnyMessage], add_messages]
    """Conversation history with automatic accumulation via add_messages reducer."""

    routing_decision: RoutingDecision | None
    """Manager Agent's routing decision (route, reasoning, context_summary). None on first entry."""

    previous_code: str
    """Previously generated code passed by Manager for CODE_MODIFICATION mode."""

    follow_up_suggestions: list[str]
    """Follow-up suggestion queries generated by Data Analysis Agent for continued exploration."""

    web_search_enabled: bool
    """Whether user toggled web search ON for this query."""

    search_sources: list[dict]
    """List of search sources: [{"title": str, "url": str}]. Populated by da_response node."""

    final_response: str
    """Final response to send back to user."""

    error: str
    """Error message if workflow fails, empty string if successful."""

    multi_file_context: str
    """Assembled multi-file context string from ContextAssembler (markdown-formatted).
    Contains file profiles, column metadata, and join hints within token budget.
    Empty string for single-file (legacy) queries."""

    file_metadata: list[dict]
    """Per-file metadata for sandbox execution: [{id, name, var_name, file_path, file_type}].
    Used by execute_in_sandbox to selectively load only needed files.
    Empty list for single-file queries."""

    session_files: list[str]
    """List of filenames linked to the current session (e.g., ["sales.csv", "customers.xlsx"]).
    Passed to Manager Agent's system prompt for routing context.
    Empty list for single-file queries."""

    session_id: str | None
    """Session UUID string if session-based flow, None for file-based (legacy) flow.
    Already used in agent_service.py initial_state but not in TypedDict."""

    # Visualization infrastructure fields (v0.4 Phase 20)
    visualization_requested: bool
    """Flag set by downstream agents when chart generation is appropriate.
    Default: False. Set by Data Analysis Agent (Phase 22) or Manager Agent hints."""

    chart_hint: str
    """User's explicit chart type preference if stated (e.g., 'bar', 'line', 'pie').
    Extracted from user_query. Empty string means chart type left to Visualization Agent.
    Default: '' (empty string)."""

    chart_code: str
    """Plotly Python code generated by Visualization Agent for chart creation.
    Separate from generated_code (which produces tabular data).
    Default: '' (no chart code)."""

    chart_specs: str
    """JSON string of Plotly figure specification from fig.to_json() output.
    Format: '{"data": [...], "layout": {...}}' (Plotly JSON schema).
    Parsed and rendered by frontend ChartRenderer component (Phase 23).
    Default: '' (no chart)."""

    chart_error: str
    """Error message if chart generation or execution fails.
    User decision: Show errors transparently, not silently.
    Default: '' (no error)."""
